apiVersion: v1
kind: Service
metadata:
  labels:
    app: valkey
  name: valkey
spec:
  ports:
  - name: valkey
    port: 6379
    protocol: TCP
    targetPort: valkey
  selector:
    app: valkey
  sessionAffinity: None
  type: ClusterIP
